HTTP/1.0 503 Service Unavailable
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html>
    <head>
        <title>FabScanPi Server is currently not running</title>
        <style>
            body {
                margin: 0;
                font-family: \"Open Sans\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;
                font-size: 14px;
                line-height: 20px;
                color: #333333;
                background-color: #ffffff;
            }
            code {
                font-family: Monaco,Menlo,Consolas,\"Courier New\",monospace;
                font-size: 12px;
                border-radius: 3px;
                padding: 2px 4px;
                color: #d14;
                white-space: nowrap;
                background-color: #f7f7f7;
                border: 1px solid #e1e1e8;
            }
            pre {
                font-family: Monaco,Menlo,Consolas,\"Courier New\",monospace;
                font-size: 12px;
                border-radius: 3px;
                padding: 2px 4px;
                white-space: nowrap;
                background-color: #f7f7f7;
                border: 1px solid #e1e1e8;
            }
            @media (max-width: 767px) {
                .wrapper {
                    padding: 20px;
                }
            }
            @media (min-width: 768px) {
                .wrapper {
                    position: absolute;
                    width: 750px;
                    height: 450px;
                    top: 50%;
                    left: 50%;
                    margin: -225px 0 0 -375px;
                }
            }
            h1 {
                line-height: 1.3;
            }

.spinner {
  margin: 100px auto 0;
  width: 70px;
  text-align: center;
}

.spinner > div {
  width: 18px;
  height: 18px;
  background-color: #333;

  border-radius: 100%;
  display: inline-block;
  -webkit-animation: sk-bouncedelay 1.4s infinite ease-in-out both;
  animation: sk-bouncedelay 1.4s infinite ease-in-out both;
}

.spinner .bounce1 {
  -webkit-animation-delay: -0.32s;
  animation-delay: -0.32s;
}

.spinner .bounce2 {
  -webkit-animation-delay: -0.16s;
  animation-delay: -0.16s;
}

@-webkit-keyframes sk-bouncedelay {
  0%, 80%, 100% { -webkit-transform: scale(0) }
  40% { -webkit-transform: scale(1.0) }
}

@keyframes sk-bouncedelay {
  0%, 80%, 100% { 
    -webkit-transform: scale(0);
    transform: scale(0);
  } 40% { 
    -webkit-transform: scale(1.0);
    transform: scale(1.0);
  }
}

        </style>

<script>

var timeoutCounter = 0;

var interval = setInterval(function() {
    ping(20)
}, 5000);

function ping(maxTimeouts){
    
    var req = new XMLHttpRequest();

    req.onreadystatechange = function() {
        if (this.readyState == 4 && this.status == 200) {
            window.location.href = window.location.href
            clearInterval(interval);
        } else {
            timeoutCounter++;

            if (timeoutCounter >= maxTimeouts) {
                    document.getElementById("booting").style.display = "none";
                    document.getElementById("error").style.display = "block";
                  //  alert("Max Timeouts ("+ maxTimeouts + ") exceeded!");
                    clearInterval(interval);
            }
        }
    };
    req.open("GET", window.location.href, true);
    req.send();
}

</script>
    </head>
    <body>
    <div id="booting" class="wrapper">
        <h1 style="text-align:center">Waiting for FabScanPi Server ...</h1>

<div class="spinner">
  <div class="bounce1"></div>
  <div class="bounce2"></div>
  <div class="bounce3"></div>
</div>

    </div>
        <div id="error" class=\"wrapper\" style="display:none;">
            <center><h1>The FabScanPi server is currently not running</h1></center>
            <p>
                If you just started up your Raspberry Pi, please wait a couple of seconds, then
                try to refresh this page.
            </p>
            <p>
                If the issue persists, please log into your Raspberry Pi via SSH and check the following:
            </p>
            <ul>
                <li>
                    Verify that the process is running:
                    <code>ps -ef | grep -i fabscanpi | grep -i python</code> should show a
                    python process:
                    <pre>pi@fabscanpi:~ $ ps -ef | grep -i fabscanpi | grep -i python<br>
root     14674     1 77 11:19 ?        00:00:02 /usr/bin/python /usr/bin/fabscanpi-serveri <br> --config=/etc/fabscanpi/default.config.json --settings=/etc/fabscanpi/defaul
t.settings.json <br> --logfile=/var/log/fabscanpi/fabscanpi.log</pre>
                </li>
                <li>
                    If it isn't, the question is why. Take a look into
                    <code>/var/log/fabscanpi/fabscanpi.log</code>, there might
                    be an error logged in there that helps to determine
                    what's wrong.
                </li>
                <li>
                    You might also want to try if you can restart the server
                    (if no obvious error is visible):
                    <code>sudo service fabscanpi restart</code>.
                </li>
            </ul>
            <p>
                If all that doesn't help to trouble shoot the issue, you can seek
                support on the <a href=\"https://fabscan.org\">FabScanPi Community Page</a>.
                Please provide your Browser version and FabScanPi version as well as your <code>fabscanpi.log</code> 
                and explain what you already tried and observed as detailed as possible.
            </p>
        </div>
    </body>
</html>